### PR TITLE
Export serve command

### PR DESCRIPTION
**Pull request by LeifAndersen**

### CODE REVIEW

**Comment by greghendershott** [comment]
Thank you very much for the pull request!

Could you also please add a section at the end of README.md, explaining this? I don't mean elaborate, detailed documentation for `serve`. I'm thinking just a paragraph explaining the motivation, the basic idea and intended use. (That would also help me review the pull request; although I have a rough idea what you have in mind, it would help me to hear you explain that.)

Even if I take a pass at it to polish the prose, it would still be a huge help if you give me a head-start, something to work with.

**Comment by LeifAndersen** [comment]
Sure, I'll add it now.

**Comment by LeifAndersen** [comment]
Added.

**Comment by greghendershott** [comment]
I'm sorry to be so slow to follow up on this!

I rebased this to `master` and merged. Thanks again!

**Pull request closed without merging**
