### PR TITLE
WIP towards authors handling

### PR DESCRIPTION
**Pull request by gasche**
I'm trying to add multi-author handling to Frog ( feature request #162 ) , but this is my first Racket hacking experience so I'm going rather slow at it. I would welcome feedback along the way: I'll push my patches when I feel they are reasonable, and rebase the PR when I have more to send -- or to make changes according to comments.

The very first patch in this PR (and for now the only one) is just changing the internal implementation of metadata parsing, with no observable change of behavior (I hope). The metadata header is parsed into an associative list.

I then tried to move the handling of mandatory fields from `meta-data` to `read-post` (my idea was to have `meta-data` be agnostic over the specific values of the metadata header, and move the mandatory/optional logic to `read-post`), but the current tests (which were very useful to me, thanks) expect `meta-data` to do the mandatory-fields checking. I'm interested in opinions on what is best: I could remove the tests and defer the mandatory-fields checking to `read-post`, or I could go the less invasive route of just adding `header` as an extra value returned by `meta-data`, so that mandatory fields are still handled there but `read-post` can extra optional fields (such as `Author`).

### CODE REVIEW

**Comment by gasche** [comment]
Ping? I haven't worked at it since this first PR, and I must say that some sort of feedback would help going forward.

**Comment by greghendershott** [comment]
@gasche Thank you very much for submitting this pull request. You caught me during a period where I've been flat-out at $NEW_DAY_JOB. Furthermore, I haven't been working on Frog for some months, so, I kept failing to find time to reload my brain enough to evaluate this and give any useful feedback.

It looks like @LeifAndersen has helped and made a new PR #164 building on your commit. If I understand correctly, I should close this PR and focus on that one @gasche ?

**Comment by LeifAndersen** [comment]
Ya, you should. The two of us work in the same lab and he has told me multiple times (in person) that I should finish this for him because he wouldn't have time for it for a bit.

**Comment by greghendershott** [comment]
@LeifAndersen OK, will close this one.

@gasche Thank you again for submitting this. I apologize for being incommunicado so long.

**Comment by gasche** [comment]
Yep, that's fine. Thanks to you and @LeifAndersen for working on this!

For the record, the reason why we need multiple-authors handling is that we're setting up a [research lab blog](http://prl.ccs.neu.edu/blog/) using Frog.

**Comment by greghendershott** [comment]
As discussed on #164 addressed this in commit 1d99938.

Thank you @gasche and @LeifAndersen !

**Pull request closed without merging**
