### PR TITLE
Support rerooting frog

### PR DESCRIPTION
**Pull request by tfeb**
Hi, I've made some changes to support rerooting frog (discussed in a previous issue I think), so blogs do not need to hang under `/`.  I'm currently maintaining my own fork with these changes: it would be a good thing, for me at least, if they were merged into the real version.  They are reasonably well tested, but I didn't understand any more of frog than I needed to in order to make them (I am reasonably familiar with Racket, so the code should not be too horrid), and haven't poked around enough since to understand if they fit into the architecture.

As such you might not want to merge *these* changes, but I think something *like* them would be good: hence this request, before I forget it.  Being slightly more pragmatic, these changes do work, don't break any existing functiionality, and are reasonably easy to drive (there's just a `uri-prefix` parameter which drives everything from the config file), so they might well do in the interim.

The two important commits are

- b3bf6e3 is the support itself.
- 322929f lets you reroot the preview server -- you want this if you ever use it with rerooted blogs.

There is a slightly spurious commit (6d562a2) whose job is just to deal with Emacs backups: it's not related to the others, although it's useful (to me) and I think innocuous. It should be on another branch really but I got lazy.

### CODE REVIEW

**Comment by willghatch** [comment]
Oh, geeze, I should have looked at the existing pull requests before adding this feature myself and adding another pull request for it.  But that said, clearly it shows that it's an important feature if two people wrote it.

**Comment by tfeb** [comment]
willghatch: If I get a chance I'll look at your fork and see how it relates to mine, then may be we could organize a single combined pull request.  I agree this is something it needs, and I'm not particularly committed to mine other than that I might have to change config in my toy blog to use some other one.

**Comment by willghatch** [comment]
@tfeb, frankly, yours is better.  Mine is more hackey in that the paths that are set up as strings I just add in a variable that may be a `.`, therefore giving stuff like /./foo.html.  I was thinking I would go back and add a function to clean it up, like your `canonicalize-url` function, but then I saw your PR.  Also I hadn't yet gotten to making the web server start with the right page up, which it looks like yours does (granted, I haven't actually tested yours yet).

**Comment by greghendershott** [comment]
@tfeb and @willghatch Thank you very much for the pull requests! I apologize for not reviewing @tfeb 's yet. I've been working on other projects lately.

---

The original use case for Frog was a simple blog-only site. Beyond that, if people wanted to add a blog to an existing domain example.com, I imagined they'd use a subdomain like blog.example.com (in which case it's fine if everything hangs off `/` there).

Later I got a couple requests to add configuration enabling you to put the blog posts and blog post index page elsewhere:

```sh
# Pattern for blog post permalinks
# Optional: Default is "/{year}/{month}/{title}.html".
# Here's an example of the Jekyll "pretty" style:
permalink = /blog/{year}/{month}/{day}/{title}/index.html
```

```sh
# The URI for the index of blog posts. Defaults to /index.html but you
# could change to e.g. /blog/index.html or /posts-index.html, and use
# some other /index.html for your site. This also effects the URI used
# in the Atom and RSS feed files for posts.
posts-index-uri = /index.html
```

However that leaves some other things still hanging at root: images, feeds, tags (more?).

So that's the status quo, I think.

---

As for this pull request: At a quick glance it looks fine, and it's great you've used it for real and done things like adjust the preview server. Thanks!

My gut tells me there are one or more bugs lurking here, re interaction with other options, that I'm just not seeing. However I think the answer to that is that I should beef up the testing.  Ideally I'd do that _before_ merging this PR. However realistically maybe I ought to merge the PR, first.

Please let me know if you have any thoughts/comments about the above?  And thanks again for the PR!

**Comment by tfeb** [comment]
I think it would better to do the testing stuff first, as there probably are bugs, and there's no advantage to merge code we think is probably broken.  I'm happy to keep tracking stuff and checking/merging against my branch as/when.  I'm never quite sure how to get GitHub to tell me about commits to repos I have pull requests against, but I can work that out I'm sure.

**Comment by greghendershott** [comment]
@tfeb OK. I've started to work on creating a test of the permutations of parameters that determine the location and/or URI path of various things. For each such permutation, it would check certain output files: Do the files exist where expected, and, inside the files are the generated URIs as expected?

Once I'm satisfied with that, for the existing parameters, I'll try merging your branch and adding the `uri-prefix` parameter to the test mix.

**Comment by tfeb** [comment]
Cool.  If there are problems or things I can help with let me know.

**Comment by willghatch** [comment]
Cool.  Thanks, Greg.

**Comment by greghendershott** [comment]
I made some progress on the testing but got detoured onto another issue; plan to resume work on this tomorrow.

Also for reference here's a link to the original issue #119: https://github.com/greghendershott/frog/issues/119

**Comment by greghendershott** [comment]
@tfeb I switched from working on the tests to trying out your PR branch.

All works well for me, except when I try to use the preview server. Can you give me a example of the values you use for:

- `output-dir`
- `uri-prefix`
- the `--root` flag?

Maybe I'm being dense but I can't find a combination that works for me with `raco frog -p`.

**Comment by greghendershott** [comment]
OK I had a typo in the `--root` arg.

What does work for me:

Use the frog example project. In its `.frogrc`, specify `output-dir = baz` and `uri-prefix = /baz`. Then, from the `example` project dir (same as where the `.frogrc` is) I do `raco frog --root . -p`.

That gets me a generic Racket web server page, which makes sense as there is no index.html up in example. But when I nav to `localhost:3000/baz/` I get the index.html down there, and navigation via links works thereafter.

**Comment by tfeb** [comment]
I think what you're doing is what should work.  Unfortunately I can't quite remember as I now have a bunch of `make` rules which do it all for me, and I've forgotten what I changed.  I will look at it either this evening or tomorrow (UK time).

**Comment by greghendershott** [comment]
@tfeb I pulled your PR branch locally so I could work on it a little bit, before eventually merging to master.

I pushed a couple commits [here](https://github.com/greghendershott/frog/commits/tfeb-uri-root-fix). Although I think they're pretty straightforward, if you have time to look at them and comment please feel free. Otherwise no worries.

**Comment by tfeb** [comment]
I think your commits are fine (I didn't know about guards on parameters!).  I am confused about branches though (almost certainly my fault).  I fetched from your repo into my local copy assuming that `tfeb-uri-root-fix` would be properly ahead of `uri-root-fix` (so once I'd fetched and made a local branch I could FF mine onto it) but it shows up as beside it (equivalent commits, different hashes).  So I've now cherry-picked *those* commits onto the original branch and pushed that.  Almost certainly this is my poor branch management: in any case it doesn't matter I think.

For the `--root` thing: what `--root` is meant to do is to tell the preview server where `/` is, so that links work.  If it doesn't know that, and the blog is rerooted, then any non-relative link breaks.  What it *should* do, in the `--preview` case is point the browser at the blog home page as well, rather than at the root.  It doesn't currently, and that's a bug.

The clean-breaking thing is clearly a bug I think: it's not clear that clean can *work* when you've changed the root, but it should not blow up.

**Comment by greghendershott** [comment]
>  I am confused about branches though (almost certainly my fault). I fetched from your repo into my local copy assuming that tfeb-uri-root-fix would be properly ahead of uri-root-fix (so once I'd fetched and made a local branch I could FF mine onto it) but it shows up as beside it (equivalent commits, different hashes). So I've now cherry-picked those commits onto the original branch and pushed that. Almost certainly this is my poor branch management: in any case it doesn't matter I think as either branch will do.

Well I'm not a master of git, and I didn't explain what I was doing.

I had made a new branch, pulled from yours, and rebased it (the last step is why the commit IDs changed).

I did this because I figured I wouldn't use the GitHub merge button. Instead I figured I'd add a few more commits, merge to master (I prefer linear, fast-forward merges), push, and mark the PR as closed manually.

**Comment by greghendershott** [comment]
> For the --root thing: what --root is meant to do is to tell the preview server where / is, so that links work. If it doesn't know that, and the blog is rerooted, then any non-relative link breaks.

That makes sense. I just got confused because I didn't start with a clear picture of the correct result. When I did get it right, I thought I'd done it wrong when preview opened on the non-existent true root page instead of the blog root page.

>  What it should do, in the --preview case is point the browser at the blog home page as well, rather than at the root. It doesn't currently, and that's a bug.

I'll add that.

**Comment by greghendershott** [comment]
I pushed commit 45b9a18.

For this to work, you still need to supply the `--root` command line flag. I wish that flag weren't necessary at all, and it could do the right thing automatically. Mulling that....

**Comment by greghendershott** [comment]
What do you think about the following code to pick a default value of the `--root` flag:

```
      (define root
        ;; Default the server root to be the number of parent dirs
        ;; above (www-path) as there are dirs in current-uri-prefix.
        (let ([depth (sub1 (length (explode-path (current-uri-prefix))))])
          (simplify-path (apply build-path (list* (www-path)
                                                  (build-list depth (λ _ 'up)))))))
```

This works for the simple cases I tried:

- `uri-prefix = /`, `output-dir = .`, `www-path = /path/to/files/`:
    - The root defaults to `/path/to/files/`
- `uri-prefix = /baz`, `output-dir = baz`, `www-path = /path/to/files/baz/`:
    - The root defaults to `/path/to/files/`

What do you think?

---

On principle I don't like `..` or `'up` with web servers -- escaping up a directory structure makes me nervous.  But:

- Realistically, most people will be using `--preview`. I highly doubt anyone would use `--serve` in production. After all, Frog is billed as a _static_ blog generator not a live blog server.

- Anyway  the `--root` flag is still available to use; this proposed change simply picks a default value for it.

**Comment by greghendershott** [comment]
Actually I may as well push that to this topic branch as a commit. See commit 805792a

**Comment by greghendershott** [comment]
Derp that commit had two problems. Need to handle `(current-uri-prefix)` being `#f`. Also, `explode-path` is provided by `racket/base` only starting in Racket 6.0. For earlier versions, need to `require` `racket/path`.

Commit 14003d0 has those changes and passes on Travis CI.

**Comment by tfeb** [comment]
This smells like the right approach: I was going to do something which let you specify both where the root was and where the blog index was, with some defaulting, but I have forgotten how that code works and got as far as it puking with a contract violation in `serve/servlet`.

I do use `--serve` in fact, but only to make a new instance of the preview server without opening a new browser tab, not in production.

**Comment by tfeb** [comment]
As of 14003d0afd20cf399895fef758c91d8c563cfcad this works really well for me: if I say `raco frog --root <my-root> -bp` the browser opens a tab on the root page for the blog and all the links work (so root is right).  So, for me, this is fine, and better than before!

**Comment by greghendershott** [comment]
Thanks for letting me know. It's also working fine on my blog, which uses [a vanilla `.frogrc`](https://github.com/greghendershott/greghendershott.github.com/blob/master/.frogrc) with no special `prefix-uri` or `output-dir` -- so the changes didn't break that config.

So the interesting question is, should I merge this to master?

I'd talked about creating tests for permutations of configuration parameters. I haven't finished that, yet. In fact as I got into it, I started to feel that a truly effective test would require a "pile of files" for each configuration permutation -- not just a combo of values in `.frogrc`, but also things like `page-template.html` customized with certain links, and so on. At that point I felt discouraged, because if the tests require that much work -- and multiplied by all the permutations -- it's not realistic that people will keep the tests updated. Hopefully I'm just being dense and will be able to think of a more elegant way to go about it. But meanwhile, I don't have any spiffy new tests to run on these changes.

Also I'm going to be challenged for time for the next 4-5 days. I think I should probably hold off on doing the merge until after that, so that if anything does break, I'll be in a position to respond quickly.

**Comment by tfeb** [comment]
Yes, I agree.  There is no urgency at all from my point of view: I would like not to have to maintain my own fork for ever if I can avoid it, but it makes no difference if it is merged now or in due course, so better to wait .

**Comment by greghendershott** [comment]
I'll definitely merge to master in a matter of days, not weeks/months.

Meanwhile I pushed commit 0d3b9af adding to README and updating the `--root` usage text.

**Comment by greghendershott** [comment]
Merged! Thanks again!!

**Comment by tfeb** [comment]
Thanks!

**Pull request closed without merging**
