### PR TITLE
example/custom.css: include a useful snippet to avoid image overflow

### PR DESCRIPTION
**Pull request by gasche**
We needed this on the PRL blog, and I don't see any situation where you would not want this by default, so I think that upstreaming it would be useful.

### CODE REVIEW

**Comment by greghendershott** [comment]
I know just enough CSS to be dangerous, so:

The `img` part seems harmless.

But I'm wondering what it means for `article` elements to max at 100%.

For example, just above in this file is some CSS that tries to let code blocks run past the right edge rather than wrap. How would these interact?

**Comment by gasche** [comment]
`article img` means any `img` that is a transitive child of `article`, I believe, the disjunction would be `article, img`.

**Comment by greghendershott** [comment]
You're right. I saw a `,` that wasn't there.

**Comment by greghendershott** [comment]
Merged -- thanks!

**Pull request merged**
